version: "3.9"
services:
    mysql_db:
        image: mysql:latest
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_DATABASE: "test-task"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
        volumes:
            - ./data:/var/lib/mysql/
